[package]
authors = ["Sebastian Garrido <sebasgarcep@gmail.com>"]
name = "ml"
version = "0.1.0"

[dependencies]
image = "0.11.1"
rand = "0.3.15"
rulinalg = "0.4.1"
rustlearn = "0.4.2"
rusty-machine = "0.5.3"
