[package]
authors = ["Sebastian Garrido <sebasgarcep@gmail.com>"]
name = "adaboost-stump"
version = "0.1.0"

[[bin]]
name = "playground"
path = "src/playground.rs"

[dependencies]
image = "0.15.0"
lazy_static = "0.2.8"
piston_window = "0.69.0"
rand = "0.3.16"
rscam = "0.5.3"
rulinalg = "0.4.2"
